config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#menu'

  namespace :admin do
    resources :menu_items
    resources :users, only: :index
    get 'orders-calendar', to: "orders_calendar#calendar"
  end

  namespace :api do
    namespace :v1 do
      get "launch_menu/(:date)", to: "launch_menu#index",
                                :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
                                :as => "launch_menu_date"
      resources :orders, defaults: { format: :json }, only: :create
    end
    namespace :outer do
      get 'orders', to: "orders#index"
      mount_devise_token_auth_for 'User', at: 'auth',
        controllers: {
          sessions: 'api/outer/devise_token_auth/sessions'
        }
    end
  end

  resources :orders, only: :index
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="container">
        <div class="alert <%= key == 'notice' ? 'alert-primary' : 'alert-danger' %>" role="alert">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
  <div class="container">
    <%= link_to "Tarragon&Sulguni launch delivery", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if user_signed_in? && !current_user.admin %>
        <button type="button" class="btn btn-light btn-sm mr-2">Your shipping address and phone in profile -></button>
      <% elsif !user_signed_in? %>
        <button type="button" class="btn btn-light btn-sm mr-2">Easy sign up to make orders -></button>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li class="dropdown-item"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li class="dropdown-item"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "btn btn-outline-secondary") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_nav_panel.html.slim
.container
  - if current_user.try(:admin)
    ul class="nav mt-2 mb-3"
      li class="nav-item"
        = link_to "Check today's orders (number: #{Order.where(created_at: Date.today.all_day).count})",
                  orders_path(:date => Date.today),class: 'btn btn-outline-primary mr-2'
      li class="nav-item"
        = link_to 'Orders history', '/admin/orders-calendar', class: 'btn btn-outline-primary mr-2'
      li class="nav-item"
        = link_to 'Users list', admin_users_path, class: 'btn btn-outline-primary mr-2'
      li class="nav-item"
        = link_to "Manage today's menu", admin_menu_items_path, class: 'btn btn-outline-primary mr-2'
  - if current_user && !current_user.admin
      - if Order.where("user_id = ?", current_user.id).where("created_at >= ?", Date.today).count > 0
        .span class="text-success" Yeah! You have some ordered yummies for today! ;)
      ul class="nav mt-2 mb-3"
        li class="nav-item"
          = link_to 'Orders history', orders_path, class: 'btn btn-outline-primary mr-2'
  - if !current_user
    | Sign in to make an order.

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container">
    <%= link_to "Tarragon&Sulguni launch delivery", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if user_signed_in? %>
        <button type="button" class="btn btn-light btn-sm mr-2">Your shipping address and phone in profile -></button>
      <% else %>
        <button type="button" class="btn btn-light btn-sm mr-2">Easy sign up to make orders -></button>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li class="dropdown-item"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li class="dropdown-item"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "btn btn-outline-secondary") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>