config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#menu'

  namespace :admin do
    resources :menu_items
    resources :users, only: :index
    get 'orders-calendar', to: "orders_calendar#calendar"
  end

  namespace :api do
    namespace :v1 do
      get "launch_menu/(:date)", to: "launch_menu#index",
                                :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
                                :as => "launch_menu_date"
      resources :orders, defaults: { format: :json }, only: :create
    end
    namespace :outer do
      get 'orders', to: "orders#index"
      mount_devise_token_auth_for 'User', at: 'auth',
        controllers: {
          sessions: 'api/outer/devise_token_auth/sessions'
        }
    end
  end

  resources :orders, only: :index
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord

  belongs_to :category
  has_and_belongs_to_many :orders
  has_many :item_histories, autosave: true, :dependent => :destroy
  has_one_attached :photo
  accepts_nested_attributes_for :photo_attachment, allow_destroy: true

  validates_numericality_of :price, :greater_than => 0.0
  validate :acceptable_image

  scope :with_attach_info, -> { with_attached_photo }
  scope :with_attach_info_and_ordered, -> { with_attached_photo.order("category_id asc, title") }
  scope :with_histories, -> (till_day) { includes(:item_histories)
                                        .where("item_histories.created_at < ?", till_day)
                                        .order("item_histories.created_at")
                                        .where("item_histories.active = ?", true)
                                        .references(:item_histories)
                                        }

  def acceptable_image
    return unless photo.attached?

    unless photo.byte_size <= 1.megabyte
      errors.add(:photo, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(photo.content_type)
      errors.add(:photo, "must be a JPEG or PNG")
    end
  end
end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < AdminController

  before_action :authenticate_user!
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  def index
    @menu_items = MenuItem.with_attach_info_and_ordered
  end

  def show
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.item_histories.build(price: @menu_item.price, active: @menu_item.active)
    @menu_item.save
    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to ['admin', @menu_item], notice: 'Menu position is added.' }
      else
        format.html { render :new, notice: 'An error occurred during adding' }
      end
    end
  end

  def update
    if @menu_item.update(menu_item_params)
      @menu_item.item_histories.build(price: @menu_item.price, active: @menu_item.active)
      @menu_item.save
    end
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to ['admin', @menu_item], notice: 'Menu position is updated.' }
      else
        format.html { render :edit, notice: 'An error occurred during the update' }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @menu_item.destroy
        format.html { redirect_to admin_menu_items_path, notice: 'Menu position is deleted.' }
      else
        format.html { render :edit, notice: 'An error occurred during deletion' }
      end
    end
  end

  private

  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def menu_item_params
    params.require(:menu_item).permit(:title, :active, :price, :category_id, :photo, photo_attachment_attributes: [:id, :_destroy])
  end
end

app/helpers/api/v1/menu_items_helper.rb
module Api::V1::MenuItemsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/admin/menu_items/_form.html.slim
= simple_form_for(['admin', @menu_item]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :price
    = f.input :active
    = f.association :category
    = f.input :photo, as: :file

  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary ml-2 mb-2'

app/views/admin/menu_items/edit.html.slim
h3 class="text-center" Edit menu position

== render 'form'

- if @menu_item.photo.attached?
  = form_for @menu_item, url: admin_menu_item_path(@menu_item) do |f|
    = f.fields_for :photo_attachment_attributes do | photo_form |
      = photo_form.hidden_field :id, value: @menu_item.photo_attachment.id
      = photo_form.hidden_field :_destroy, value: true
    = f.submit "Delete photo"
  br

=< link_to 'To the full menu', admin_menu_items_path, class: 'btn btn-outline-secondary ml-2'

app/views/admin/menu_items/index.html.slim
p#notice = notice

h3 class="text-center"  Full menu and today's items availabilty

= link_to 'Add position', new_admin_menu_item_path, class: 'btn btn-success float-right mb-3'

table.table.table-striped
  thead
    tr
      th
      th Title
      th Category
      th Price
      th Available?
      th
      th
      th

  tbody
    - @menu_items.each do |menu_item|
      tr
        td
          - if menu_item.photo.attached?
            = image_tag(menu_item.photo, size: '160x120')
        td = menu_item.title
        td = menu_item.category_id
        td = number_to_currency(menu_item.price)
        td = menu_item.active
        td = link_to 'Show', admin_menu_item_path(menu_item), class: 'btn btn-outline-primary btn-sm'
        td = link_to 'Edit', edit_admin_menu_item_path(menu_item), class: 'btn btn-outline-success btn-sm'
        td = link_to 'Delete', admin_menu_item_path(menu_item), data: { confirm: 'Are you sure?!' }, method: :delete, class: 'btn btn-outline-danger btn-sm'

br

app/views/admin/menu_items/new.html.slim
h3 class="text-center" New menu position

== render 'form'

=< link_to 'Back', :back, class: 'btn btn-outline-secondary ml-2'

app/views/admin/menu_items/show.html.slim
p#notice = notice

p
  strong Menu position
- if @menu_item.photo.attached?
  p
    = image_tag(@menu_item.photo, size: '200x150')
p
  strong Title:
  = @menu_item.title
p
  strong Category:
  = @menu_item.category_id
p
  strong Price:
  = number_to_currency(@menu_item.price)
p
  strong Available:
  = @menu_item.active
p

=> link_to 'Edit', edit_admin_menu_item_path(@menu_item), class: 'btn btn-success mb-3'
br

=< link_to 'To the full menu', admin_menu_items_path, class: 'btn btn-outline-secondary'